Enabling get_annotations to use export v2
Labelbox/labelsnow pull request #6
Opened 2024-05-20 20:26 UTC by ramy1951

A breaking change that includes enabling exports v2 to be used for annotation export. The breaking change is in the DataFrame columns being exported. The new column mapping for export v2 does not match export v1 and the client code using this library will need to be adjusted. 

Outlined below is the breaking change:
- Previously exported annotations included the columns below:
```
{
    'ID': 'string',
    'DataRow ID': 'string',
    'Labeled Data': 'string',
    'Created By': 'string',
    'Project Name': 'string',
    'Seconds to Label': 'float64',
    'External ID': 'string',
    'Agreement': 'int64',
    'Benchmark Agreement': 'int64',
    'Benchmark ID': 'string',
    'Dataset Name': 'string',
    'Reviews': 'object',
    'View Label': 'string',
    'Has Open Issues': 'int64',
    'Skipped': 'bool'
}
```

- The new column keys are:
```
{
    'data_row': 'object',
    'media_attributes': 'object',
    'projects': 'object',
}
```

2024-06-06 18:21 UTC, paulnoirel requested changes
After testing demo/demo.py, the new format for `LABELBOX_DEFAULT_TYPE_DICTIONARY` breakshttps://github.com/Labelbox/labelsnow/blob/main/labelsnow/silver_table.py#L84 since the dictionaries are different

2024-06-06 21:26 UTC, ramy1951 commented
@paulnoirel I fixed this issue. This is a hidden dependency on that table since someone takes the same Dataframe passing it to another function.

2024-06-07 13:05 UTC, paulnoirel requested changes
Thanks for making the changes!

Unfortunately.... I think you need to change this one too `labelsnow/get_videoframe_annotations.py` since it uses the old format for exports.

2024-06-11 18:31 UTC, ramy1951 commented
I updated `labelsnow/get_videoframe_annotations.py`
Here is the code I used to test with it. `video_bronze` is a simulated output from the function that would be called before it in the demo.py file.

```
video_bronze = {'data_row': {0: {'id': 'clxanhonn0nl7075332mp13wa', 'global_key': 'sample-video-jellyfish.mp4c0566e6a-55fb-4df7-9f8a-249708492359', 'row_data': 'https://storage.googleapis.com/labelbox-datasets/video-sample-data/sample-video-2.mp4'}}, 'media_attributes': {0: {'height': 1080, 'width': 1920, 'asset_type': 'video', 'mime_type': 'video/mp4', 'frame_rate': 10, 'frame_count': 100}}, 'projects': {0: {'clxanhx3c0bc607yn15txfoz0': {'name': 'Video Annotation Import Demo', 'labels': [{'label_kind': 'Video', 'version': '1.0.0', 'id': 'clxani2hj001c19wn9y9j32fo', 'annotations': {'frames': {'29': {'objects': {}, 'classifications': [{'feature_id': 'clxani2gv000d19wn511f2v5b', 'feature_schema_id': 'clxanhwqf04bs07y11w407ec0', 'name': 'checklist_class', 'value': 'checklist_class', 'checklist_answers': [{'feature_id': 'clxani2gv000e19wnlbqokca8', 'feature_schema_id': 'clxanhwqf04bt07y1cng5hu0j', 'name': 'first_checklist_answer', 'value': 'first_checklist_answer', 'classifications': []}, {'feature_id': 'clxani2gv000f19wnuxw4hqtn', 'feature_schema_id': 'clxanhwqf04bv07y1d24r7kuc', 'name': 'second_checklist_answer', 'value': 'second_checklist_answer', 'classifications': []}]}]}, '35': {'objects': {}, 'classifications': [{'feature_id': 'clxani2gv000d19wn511f2v5b', 'feature_schema_id': 'clxanhwqf04bs07y11w407ec0', 'name': 'checklist_class', 'value': 'checklist_class', 'checklist_answers': [{'feature_id': 'clxani2gv000e19wnlbqokca8', 'feature_schema_id': 'clxanhwqf04bt07y1cng5hu0j', 'name': 'first_checklist_answer', 'value': 'first_checklist_answer', 'classifications': []}, {'feature_id': 'clxani2gv000f19wnuxw4hqtn', 'feature_schema_id': 'clxanhwqf04bv07y1d24r7kuc', 'name': 'second_checklist_answer', 'value': 'second_checklist_answer', 'classifications': []}]}]}, '9': {'objects': {}, 'classifications': [{'feature_id': 'clxani2gv000g19wnifrl78k6', 'feature_schema_id': 'clxanhwqf04by07y1dr0h3sfm', 'name': 'radio_class', 'value': 'radio_class', 'radio_answer': {'feature_id': 'clxani2gv000h19wn811bpg4s', 'feature_schema_id': 'clxanhwqf04bz07y13d1pfhde', 'name': 'first_radio_answer', 'value': 'first_radio_answer', 'classifications': []}}]}, '15': {'objects': {}, 'classifications': [{'feature_id': 'clxani2gv000g19wnifrl78k6', 'feature_schema_id': 'clxanhwqf04by07y1dr0h3sfm', 'name': 'radio_class', 'value': 'radio_class', 'radio_answer': {'feature_id': 'clxani2gv000h19wn811bpg4s', 'feature_schema_id': 'clxanhwqf04bz07y13d1pfhde', 'name': 'first_radio_answer', 'value': 'first_radio_answer', 'classifications': []}}]}, '13': {'objects': {'clxani2gv000i19wndrr33i92': {'feature_id': 'clxani2gv000i19wndrr33i92', 'feature_schema_id': 'clxanhwqe04b807y19k1x0jex', 'name': 'bbox_video', 'value': 'bbox_video', 'annotation_kind': 'VideoBoundingBox', 'classifications': [], 'bounding_box': {'top': 617.0, 'left': 1371.0, 'height': 419.0, 'width': 505.0}}, 'clxani2gv000j19wnxuo8cgkv': {'feature_id': 'clxani2gv000j19wnxuo8cgkv', 'feature_schema_id': 'clxanhwqf04bg07y1g9rv85gy', 'name': 'bbox_class', 'value': 'bbox_class', 'annotation_kind': 'VideoBoundingBox', 'classifications': [{'feature_id': 'clxani2gv000k19wnpila1m60', 'feature_schema_id': 'clxanhwqf04bh07y1ew3543sh', 'name': 'checklist_class', 'value': 'checklist_class', 'radio_answer': {'feature_id': 'clxani2gv000m19wnp1strqxt', 'feature_schema_id': 'clxanhwqf04bk07y1gogd25kw', 'name': 'second_checklist_answer', 'value': 'second_checklist_answer', 'classifications': []}}], 'bounding_box': {'top': 146.0, 'left': 98.0, 'height': 382.0, 'width': 341.0}}}, 'classifications': []}, '19': {'objects': {'clxani2gv000i19wndrr33i92': {'feature_id': 'clxani2gv000i19wndrr33i92', 'feature_schema_id': 'clxanhwqe04b807y19k1x0jex', 'name': 'bbox_video', 'value': 'bbox_video', 'annotation_kind': 'VideoBoundingBox', 'classifications': [], 'bounding_box': {'top': 617.0, 'left': 1371.0, 'height': 419.0, 'width': 505.0}}}, 'classifications': []}, '10': {'objects': {'clxani2gv000j19wnxuo8cgkv': {'feature_id': 'clxani2gv000j19wnxuo8cgkv', 'feature_schema_id': 'clxanhwqf04bg07y1g9rv85gy', 'name': 'bbox_class', 'value': 'bbox_class', 'annotation_kind': 'VideoBoundingBox', 'classifications': [], 'bounding_box': {'top': 146.0, 'left': 98.0, 'height': 382.0, 'width': 341.0}}}, 'classifications': []}, '22': {'objects': {'clxani2gv000n19wncq1mmgg8': {'feature_id': 'clxani2gv000n19wncq1mmgg8', 'feature_schema_id': 'clxanhwqe04b807y19k1x0jex', 'name': 'bbox_video', 'value': 'bbox_video', 'annotation_kind': 'VideoBoundingBox', 'classifications': [], 'bounding_box': {'top': 617.0, 'left': 1371.0, 'height': 419.0, 'width': 505.0}}, 'clxani2gv000o19wnfg949yb9': {'feature_id': 'clxani2gv000o19wnfg949yb9', 'feature_schema_id': 'clxanhwqe04b807y19k1x0jex', 'name': 'bbox_video', 'value': 'bbox_video', 'annotation_kind': 'VideoBoundingBox', 'classifications': [], 'bounding_box': {'top': 146.0, 'left': 98.0, 'height': 382.0, 'width': 341.0}}}, 'classifications': []}, '27': {'objects': {'clxani2gv000n19wncq1mmgg8': {'feature_id': 'clxani2gv000n19wncq1mmgg8', 'feature_schema_id': 'clxanhwqe04b807y19k1x0jex', 'name': 'bbox_video', 'value': 'bbox_video', 'annotation_kind': 'VideoBoundingBox', 'classifications': [], 'bounding_box': {'top': 617.0, 'left': 1371.0, 'height': 419.0, 'width': 505.0}}, 'clxani2gv000o19wnfg949yb9': {'feature_id': 'clxani2gv000o19wnfg949yb9', 'feature_schema_id': 'clxanhwqe04b807y19k1x0jex', 'name': 'bbox_video', 'value': 'bbox_video', 'annotation_kind': 'VideoBoundingBox', 'classifications': [], 'bounding_box': {'top': 146.0, 'left': 98.0, 'height': 382.0, 'width': 341.0}}}, 'classifications': []}, '17': {'objects': {'clxani2gv000p19wn1wdrm7no': {'feature_id': 'clxani2gv000p19wn1wdrm7no', 'feature_schema_id': 'clxanhwqe04ba07y1cxnycujo', 'name': 'point_video', 'value': 'point_video', 'annotation_kind': 'VideoPoint', 'classifications': [], 'point': {'x': 660.134, 'y': 407.926}}}, 'classifications': []}, '5': {'objects': {'clxani2gv000q19wnnze6t07g': {'feature_id': 'clxani2gv000q19wnnze6t07g', 'feature_schema_id': 'clxanhwqf04bc07y1a9nth8hp', 'name': 'line_video_frame', 'value': 'line_video_frame', 'annotation_kind': 'VideoPolyline', 'classifications': [], 'line': [{'x': 680.0, 'y': 100.0}, {'x': 100.0, 'y': 190.0}]}}, 'classifications': []}, '20': {'objects': {'clxani2gv000q19wnnze6t07g': {'feature_id': 'clxani2gv000q19wnnze6t07g', 'feature_schema_id': 'clxanhwqf04bc07y1a9nth8hp', 'name': 'line_video_frame', 'value': 'line_video_frame', 'annotation_kind': 'VideoPolyline', 'classifications': [], 'line': [{'x': 680.0, 'y': 100.0}, {'x': 100.0, 'y': 190.0}]}, 'clxani2gw001919wnp49l2v7k': {'feature_id': 'clxani2gw001919wnp49l2v7k', 'feature_schema_id': 'clxanhwqf04be07y1ddvxbkx8', 'name': 'video_mask', 'value': 'video_mask', 'annotation_kind': 'VideoSegmentationMask', 'classifications': [], 'mask': {'url': 'https://api.labelbox.com/api/v1/projects/clxanhx3c0bc607yn15txfoz0/annotations/clxani2gw001919wnp49l2v7k/index/20/mask'}, 'composite_mask': {'url': 'https://api.labelbox.com/api/v1/tasks/clxankgav01gz07x01g2k22pk/masks/clxanhzvd000c19wn0t6heqgt/index/20', 'color_rgb': [76, 104, 177]}}, 'clxani2gw001a19wnb931wufz': {'feature_id': 'clxani2gw001a19wnb931wufz', 'feature_schema_id': 'clxanhwqf04bo07y178f3gedm', 'name': 'mask_with_text_subclass', 'value': 'mask_with_text_subclass', 'annotation_kind': 'VideoSegmentationMask', 'classifications': [], 'mask': {'url': 'https://api.labelbox.com/api/v1/projects/clxanhx3c0bc607yn15txfoz0/annotations/clxani2gw001a19wnb931wufz/index/20/mask'}, 'composite_mask': {'url': 'https://api.labelbox.com/api/v1/tasks/clxankgav01gz07x01g2k22pk/masks/clxanhzvd000c19wn0t6heqgt/index/20', 'color_rgb': [233, 218, 94]}}, 'clxani2gw001b19wn7awd1gbt': {'feature_id': 'clxani2gw001b19wn7awd1gbt', 'feature_schema_id': 'clxanhwqf04b [...]

2024-06-11 18:58 UTC, paulnoirel reviewed
Do we went to update the `applymap` in https://github.com/Labelbox/labelsnow/blob/main/labelsnow/flatten_bronze_table.py#L9 and https://github.com/Labelbox/labelsnow/blob/main/labelsnow/flatten_bronze_table.py#L23 ?

2024-06-11 19:57 UTC, paulnoirel requested changes
All good except that `get_videoframe_annotations()` will fail if the project doesn't have any `VideoSegmentationMask`:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-16-127b01cc4188>](https://localhost:8080/#) in <cell line: 5>()
      3 video_bronze = labelsnow.get_annotations(
      4     client, "cl5mp75op0z0k07xjc0ufckl4")  #sample completed video project
----> 5 video_dataframe_framesets = get_videoframe_annotations(
      6     video_bronze, "cl5mp75op0z0k07xjc0ufckl4")
      7 silver_video_dataframes = {}

1 frames
[<ipython-input-15-74492c0e46a9>](https://localhost:8080/#) in get_videoframe_annotations(bronze_video_labels, project_id)
     45         # df = pd.json_normalize(data) #had to use this b/c the data is a list of json objects
     46         # df = df.astype(LABELBOX_DEFAULT_TYPE_DICTIONARY)
---> 47         df = pd.DataFrame.from_dict(data).astype(
     48             {'DataRow ID': 'string'})  #create pandas DF with proper col type
     49         array_of_bronze_dataframes.append(df)  #create array of bronze tables

[/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py](https://localhost:8080/#) in astype(self, dtype, copy, errors)
   6603             for col_name in dtype_ser.index:
   6604                 if col_name not in self:
-> 6605                     raise KeyError(
   6606                         "Only a column name can be used for the "
   6607                         "key in a dtype mappings argument. "

KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'DataRow ID' not found in columns."
```

2024-06-12 18:23 UTC, paulnoirel approved these changes
LGTM, thanks.
We'll just have to bear in mind that the different versions of pandas between `labelbox` and `labelsnow` may cause some problems...

2024-06-12 18:24 UTC, merged